version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
#Static Application Security Scan (SAST scan) using SonarCloud
      - echo "Running static code analysis with SonarCloud"
      - mvn verify sonar:sonar -Dsonar.projectKey=sonartest13_sonartest13 -Dsonar.organization=SonarTest13 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=b73c0cd5c726079111dcf572e0d1c16fb6937f96


