version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
#Static Application Security Scan (SAST scan) using SonarCloud
      - echo "Running static code analysis with SonarCloud"
      - mvn verify sonar:sonar -Dsonar.projectKey=tes-test -Dsonar.organization=Test -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=7e2293f22878b2ae81895fbb992cde7913f1eb83


